apiVersion: batch/v1
kind: Job
metadata:
  name: app-validation-{{ .Release.Revision }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: run-validation
        image: alpine:latest
        command: ["echo fail", "sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0