apiVersion: batch/v1
kind: Job
metadata:
  name: app-validation-{{ .Release.Revision }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: run-validation
        image: curlimages/curl
        command:
          - "echo my sync was successful and I ran"
      restartPolicy: Never
  backoffLimit: 2