apiVersion: batch/v1
kind: Job
metadata:
  name: app-validation-{{ .Release.Revision }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: run-validation
        image: alpine:latest
        command: 
          - "echo"
          - "Im running"
          - "sleep"
          - "10"
          - "exit"
          - 5
      restartPolicy: Never
  backoffLimit: 0